import { useEffect, useState } from 'react';
import AdminHome from '../admin/AdminHome';
import FastPosCheckoutModal from '../admin/FastPosCheckoutModal';
import CameraBarcodeScannerModal from '../admin/CameraBarcodeScannerModal';
import type { PosSaleData } from '../admin/FastPosCheckoutModal';
import type { Product, Order, Quote, CariAccount } from '../../types';
import { Select, Modal, Button } from './index';
const products: Product[] = [{ id: 'sample-1', name: 'Pirinç dirsek', category: 'Bağlantı', description: 'Örnek ürün', price: 120, stock: 2, unit: 'ADET', sku: 'ORNEK-01', barcode: '8690000000001', minOrderQuantity: 1, imageUrl: '' }, { id: 'sample-2', name: 'Endüstriyel güçlendirilmiş tesisat bağlantı adaptörü ' + 'A'.repeat(80), category: 'Bağlantı', description: 'Örnek ürün', price: 285, stock: 8, unit: 'ADET', sku: 'ORNEK-02', barcode: '8690000000002', minOrderQuantity: 1, imageUrl: '' }, { id: 'sample-3', name: 'Stoksuz vana', category: 'Vanalar', description: 'Örnek ürün', price: 450, stock: 0, unit: 'ADET', sku: 'ORNEK-03', minOrderQuantity: 1, imageUrl: '' }];
const order: Order = { id: 'sample-order', orderNumber: 'ÖRNEK-2026-1', customerName: 'Örnek Müşteri', customerEmail: 'ornek@example.com', subtotal: 120, discount: 0, tax: 20, customerPhone: '05550000000', customerAddress: 'Örnek adres', items: [], total: 120, receiptStatus: 'uploaded', status: 'pending', createdAt: '2026-09-14T10:00:00Z', updatedAt: '2026-09-14T10:00:00Z' };
const quote: Quote = { id: 'sample-quote', quoteNumber: 'ÖRNEK-TEKLİF', customerName: 'Örnek Müşteri', customerEmail: 'ornek@example.com', customerPhone: '05550000000', deliveryCity: 'İstanbul', requestedItems: [], taxRate: 20, status: 'pending_review', createdAt: order.createdAt, updatedAt: order.updatedAt };
const account: CariAccount = { id: 'sample-account', code: 'ÖRNEK', name: 'Örnek Yetkili', companyName: 'Örnek Mekanik ve Endüstriyel Yapı Malzemeleri Limited Şirketi', type: 'customer', phone: '05550000000', email: 'ornek@example.com', city: 'İstanbul', creditLimit: 10000, paymentTermDays: 30, balance: 0, totalDebit: 0, totalCredit: 0, status: 'active', createdAt: order.createdAt, updatedAt: order.updatedAt };
const accountsReady = async () => [account], accountsEmpty = async () => [], accountsError = async () => { throw new Error('Örnek hata'); };
const accountsLoading = () => new Promise<CariAccount[]>(() => { });
export default function OperationsPreview() {
    const [cameraOpen, setCameraOpen] = useState(false);
    const [scan, setScan] = useState<{ code: string; sequence: number } | null>(null);
    const [theme, setTheme] = useState('light'), [scenario, setScenario] = useState('ready'), [open, setOpen] = useState(false), [destination, setDestination] = useState(''), [calls, setCalls] = useState(0), [stock, setStock] = useState(products);
    useEffect(() => { document.documentElement.dataset.theme = theme; document.body.classList.add('ui-preview-active'); return () => { delete document.documentElement.dataset.theme; document.body.classList.remove('ui-preview-active'); }; }, [theme]);
    const complete = async (data: PosSaleData) => { setCalls(n => n + 1); await new Promise(resolve => setTimeout(resolve, 1200)); if (scenario === 'save-error')
        throw new Error('Örnek kayıt hatası'); return { ...order, id: 'sample-result', orderNumber: 'ÖRNEK-POS-001', total: scenario === 'mismatch' ? data.totalAmount * 1.2 : data.totalAmount, tax: Math.round(data.totalAmount * 20 / 120), customerName: data.customerName, items: data.items.map(i => ({ ...i, productName: products.find(p => p.id === i.productId)!.name, unit: 'ADET' })) }; };
    return <main className="ui-scope ui-preview"><div className="ui-preview-header"><p>Faz 4F · Tamamen örnek veriler · Gerçek satış yapılmaz</p><Select label="Tema" value={theme} onChange={e => setTheme(e.target.value)}><option value="light">Açık</option><option value="dark">Koyu</option></Select><Select label="Senaryo" value={scenario} onChange={e => { setScenario(e.target.value); setCalls(0); setStock(products); setOpen(false); }}>{[['ready', 'Normal'], ['empty', 'Boş'], ['loading', 'Yükleniyor'], ['error', 'Ürün hatası'], ['save-error', 'Kayıt hatası'], ['accounts-error', 'Cari hatası'], ['accounts-empty', 'Cari yok'], ['accounts-loading', 'Cariler yükleniyor'], ['mismatch', 'Sunucu tutarı farklı']].map(([id, label]) => <option key={id} value={id}>{label}</option>)}</Select><p>Örnek kayıt çağrısı: <output data-testid="sale-calls">{calls}</output></p></div>
 <AdminHome products={scenario === 'empty' ? [] : stock} orders={scenario === 'empty' ? [] : [order]} quotes={scenario === 'empty' ? [] : [quote]} loading={scenario === 'loading'} error={scenario === 'error' ? 'Örnek bağlantı hatası.' : undefined} onRetry={() => setScenario('ready')} onNavigate={setDestination} onPos={() => setOpen(true)}/>
 <div key={scenario}><FastPosCheckoutModal scannedBarcode={scan} onOpenBarcodeScanner={() => setCameraOpen(true)} isOpen={open} onClose={() => setOpen(false)} products={scenario === 'empty' ? [] : stock} onCompleteSale={complete} loadAccounts={scenario === 'accounts-error' ? accountsError : scenario === 'accounts-empty' ? accountsEmpty : scenario === 'accounts-loading' ? accountsLoading : accountsReady} loading={scenario === 'loading'} error={scenario === 'error' ? 'Örnek bağlantı hatası.' : undefined} onRetry={() => setScenario('ready')}/></div>
 <CameraBarcodeScannerModal isOpen={cameraOpen} onClose={() => setCameraOpen(false)} products={stock} onScannedProduct={(_, code) => { setScan(previous => ({ code, sequence: (previous?.sequence || 0) + 1 })); setCameraOpen(false); }} />
 <div className="ops-actions"><Button variant="secondary" onClick={() => setStock(prev => prev.map(p => ({ ...p, stock: 0 })))}>Örnek stokları sıfırla</Button></div><Modal open={!!destination} onClose={() => setDestination('')} title="Örnek yönetim bağlantısı"><p>Seçilen araç: {destination}. Canlı uygulamadaki mevcut yönetim ekranına bağlanır.</p><p>Bu önizlemede durum değişikliği yapılmaz.</p></Modal></main>;
}
